#!/bin/bash

# caelestia:summary=Launch or focus on a given web app identified by the window-pattern.
# caelestia:args=<window-pattern> <url-and-flags...>

if (($# == 0)); then
  echo "Usage: launch-or-focus-webapp [window-pattern] [url-and-flags...]"
  exit 1
fi

WINDOW_PATTERN="$1"
shift

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
LAUNCH_COMMAND="$script_dir/webapp-launch $@"

exec "$script_dir/launch-or-focus" "$WINDOW_PATTERN" "$LAUNCH_COMMAND"
